### ISSUE TITLE
retrofit网络请求应该放在哪一层？

### ISSUE THREAD

**Issue by liaopen123** [xybCoder/gank#4]
正在学MVP，发现gank项目中的网络请求写在了presenter层，但是看其他技术博客对model层的介绍是：Model层负责获取或存储在远程或本地的数据。那么按道理的话 网络请求应该是在model层请求的    有点疑惑。

> gank项目中的GankPresenter的fetchGankData方法是retrofit请求网络的。

**Comment by xybCoder** [comment]
获取数据放在M层也可以，我放在P层主要考虑P层处理逻辑，其实具体放那一层也没有硬性规定，看个人理解。
