### ISSUE TITLE
presenter 的 release 方法

### ISSUE THREAD

**Issue by Olaman** [xybCoder/gank#5]
BasePresenter 里面 protected T iView; 直接持有一个 ivew.

那么它的 release 方法应该在 baseactivity的 ondestroy 执行, 解绑 presenter 和 ivew?
如果不执行, 应该是 presenter 一直持有 activity 的实例了, 有内存泄漏的风险?

谢谢

**Comment by xybCoder** [comment]
en, 是应该在 ondestroy解绑并置null释放
