### ISSUE TITLE
我正在看你的项目，有些不懂的。能否有偿向你提问下呢？有偿，谢谢！

### ISSUE THREAD

**Issue by sunreview** [xybCoder/gank#7]
我正在看你的项目，有些不懂的。能否有偿向你提问下呢？有偿，谢谢！

**Comment by xybCoder** [comment]
开源就是大家相互学习，你说，尽力给你解释清楚

TomRidder <notifications@github.com> 于2019年6月26日周三 上午11:24写道：

**Comment by sunreview** [comment]
你太够哥们了！
