### ISSUE TITLE
hosttype是什么逻辑呢

### ISSUE THREAD

**Issue by sunreview** [xybCoder/gank#8]
hosttype是什么逻辑呢

**Comment by xybCoder** [comment]
满足app不同业务可能host不一样，例如 新闻是 www.news?xxxxxx;行情是www.trade?xxx

TomRidder <notifications@github.com> 于2019年6月26日周三 上午11:25写道：

**Comment by sunreview** [comment]
public class HostType {
    //多少种Host类型
    public static final int TYPE_COUNT = 3;

    //网易新闻视频的host
    @HostTypeChecker
    public static final int GANK_TYPE = 1;

    //新浪图片的HOST
    @HostTypeChecker
    public static final int NEWS_TYPE = 2;


    /**
     * 替代枚举的方案，使用IntDef保证类型安全
     */
    @IntDef({GANK_TYPE, NEWS_TYPE})
    @Retention(RetentionPolicy.SOURCE)
    public @interface HostTypeChecker { }
}

hostType这里的代码注解看的不是很懂，你用的是什么开源框架的，我先去看看

**Comment by xybCoder** [comment]
不是第三方库，java注解

**Comment by sunreview** [comment]
@IntDef({GANK_TYPE, NEWS_TYPE}) 应该是int类型的枚举

  @Retention(RetentionPolicy.SOURCE)
    public @interface HostTypeChecker { } 这个自定义注解是什么作用呢呢

**Comment by sunreview** [comment]
大兄弟 回答下我啊

**Comment by xybCoder** [comment]
就是自定义注解替换枚举，其实你也可以单独定义final常量，可以不用我这种方式
