### ISSUE TITLE
问一下  volatile 啥作用呢

### ISSUE THREAD

**Issue by sunreview** [xybCoder/gank#9]
private static volatile OkHttpClient sOkHttpClient;
这一句中的 volatile 啥作用呢

**Comment by xybCoder** [comment]
volatile作为java中的关键词之一，用以声明变量的值可能随时会别的线程修改，使用volatile修饰的变量会强制将修改的值立即写入主存，主存中值的更新会使缓存中的值失效
               建议你看一下java编程思想

**Comment by sunreview** [comment]
嗯嗯，谢谢大佬。问一下RetrofitManager的代码都是你写的吗？看得我云里雾里。。。

**Comment by tomridder** [comment]
`  @Override
    public void onBindViewHolder(GanHuoAdapter.GanHuoHolder holder, int position)
    {
        Gank gank = gankList.get(position);
        holder.tvDescWithWho.setTag(gank);
        holder.tvDescWithWho.setText(StringStyleUtil.getGankStyleStr(gank));
    }`
这段代码中的setTag什么作用呢，我之前写recyclerView从来没用过

**Comment by sunreview** [comment]
`
  @Override
    public void onBindViewHolder(GanHuoAdapter.GanHuoHolder holder, int position)
    {
        Gank gank = gankList.get(position);
        holder.tvDescWithWho.setTag(gank);
        holder.tvDescWithWho.setText(StringStyleUtil.getGankStyleStr(gank));
    }
`
这段代码中的setTag什么作用呢，我之前写recyclerView从来没用过

**Comment by sunreview** [comment]
你好 能否加下我的qq呢 我有些问题想要问你 1402709211

**Comment by xybCoder** [comment]
> `@Override public void onBindViewHolder(GanHuoAdapter.GanHuoHolder holder, int position) { Gank gank = gankList.get(position); holder.tvDescWithWho.setTag(gank); holder.tvDescWithWho.setText(StringStyleUtil.getGankStyleStr(gank)); }`
> 这段代码中的setTag什么作用呢，我之前写recyclerView从来没用过

settag是把数据存到控件中
在代码中有用到
 @OnClick(R.id.ll_ganhuo)
        void toWebClick() {
            WebActivity.loadWebViewActivity(context, (Gank) tvDescWithWho.getTag());
        }

**Comment by xybCoder** [comment]
> 你好 能否加下我的qq呢 我有些问题想要问你 1402709211

大兄弟你是计算机专业吗
